import { useState } from "react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { Activity, ArrowUpRight, Bot, LockKeyhole, Radio, ShieldCheck, Zap } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AgentPortrait, BudgetRing, Panel, SectionTitle, SecurityItem, StatusBadge } from "@/components/agentpay-ui";
import { PaymentDetail } from "@/components/payment-detail";
import { PaymentFlow } from "@/components/payment-flow";
import { payments, spendData, type Payment } from "@/lib/agentpay-data";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

const pie = [{ name: "Translation", value: 2, color: "var(--cyan)" }, { name: "Compute", value: 4, color: "var(--purple)" }, { name: "Storage", value: 3, color: "var(--warning)" }];

export function DashboardPage() {
  const [selected, setSelected] = useState<Payment | null>(null);
  return <AppShell title="Autonomous Payment Control"><div className="mb-6 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="max-w-2xl text-sm text-muted-foreground">Live policy enforcement for AGENT-01. Every transfer is checked by immutable budget logic before settlement.</p></div><div className="flex items-center gap-2 font-mono text-[10px] text-cyan"><Radio className="size-3.5 animate-pulse"/>LIVE · BLOCK 18,942,110</div></div>
    <div className="grid gap-4 xl:grid-cols-12">
      <Panel className="relative overflow-hidden xl:col-span-4"><div className="absolute -bottom-16 -right-8 size-56 rounded-full bg-cyan/[.05] blur-2xl"/><SectionTitle eyebrow="Active entity" title="Agent status" action={<StatusBadge status="Online"/>}/><div className="flex items-center gap-5"><AgentPortrait className="size-28 shrink-0"/><div><h3 className="font-display text-xl font-bold">AGENT-01</h3><p className="mt-1 text-sm text-muted-foreground">Autonomous procurement</p><div className="mt-4 flex gap-2"><span className="mini-stat"><Bot/>12 tasks</span><span className="mini-stat"><Zap/>8.4s avg</span></div></div></div></Panel>
      <Panel className="xl:col-span-4"><SectionTitle eyebrow="Policy contract" title="Budget overview"/><div className="flex items-center justify-around gap-4"><BudgetRing/><div className="space-y-3"><div><p className="hud-label">Spent</p><p className="font-display text-2xl font-bold">9.00 <small>USDC</small></p></div><div><p className="hud-label">Remaining</p><p className="font-display text-xl font-bold text-cyan">1.00 <small>USDC</small></p></div></div></div><div className="mt-4 flex items-center justify-center gap-2 border-t border-border pt-4 text-xs text-muted-foreground"><LockKeyhole className="size-3.5 text-cyan"/>Hard cap enforced on-chain</div></Panel>
      <Panel className="xl:col-span-4"><SectionTitle eyebrow="Live feed" title="Payment activity" action={<Activity className="size-4 text-cyan"/>}/><div className="space-y-1">{payments.slice(0,4).map((p, i) => <button key={p.id} onClick={() => setSelected(p)} className="activity-row"><span className={p.status === "Blocked" ? "activity-dot-blocked" : "activity-dot"}/><div className="min-w-0 flex-1 text-left"><p className="truncate text-xs font-medium">{p.service} · {p.provider}</p><p className="font-mono text-[9px] text-muted-foreground">{p.time}</p></div><div className="text-right"><p className="font-mono text-xs font-semibold">{p.amount} USDC</p><span className={p.status === "Blocked" ? "text-[9px] text-destructive" : "text-[9px] text-cyan"}>{p.status}</span></div></button>)}</div></Panel>
      <Panel className="xl:col-span-8"><SectionTitle eyebrow="x402 protocol" title="Payment flow visualizer"/><PaymentFlow/></Panel>
      <Panel className="xl:col-span-4"><SectionTitle eyebrow="Defense matrix" title="Security status"/><SecurityItem>Hard cap active</SecurityItem><SecurityItem>On-chain enforcement</SecurityItem><SecurityItem>Replay protection</SecurityItem><SecurityItem>Delivery verification</SecurityItem></Panel>
      <Panel className="xl:col-span-7"><SectionTitle eyebrow="Ledger" title="Recent purchases"/><Table><TableHeader><TableRow><TableHead>Service</TableHead><TableHead>Provider</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader><TableBody>{payments.slice(0,4).map((p) => <TableRow key={p.id} className="cursor-pointer" onClick={() => setSelected(p)}><TableCell className="font-medium">{p.service}</TableCell><TableCell className="text-muted-foreground">{p.provider}</TableCell><TableCell><StatusBadge status={p.status}/></TableCell><TableCell className="text-right font-mono">{p.amount.toFixed(2)} USDC <ArrowUpRight className="ml-1 inline size-3"/></TableCell></TableRow>)}</TableBody></Table></Panel>
      <Panel className="xl:col-span-5"><SectionTitle eyebrow="Telemetry" title="Spending over time"/><div className="h-[225px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={spendData}><defs><linearGradient id="spend" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--cyan)" stopOpacity={.35}/><stop offset="1" stopColor="var(--cyan)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="time" stroke="var(--muted-foreground)" fontSize={10}/><YAxis stroke="var(--muted-foreground)" fontSize={10}/><ChartTooltip contentStyle={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 6 }}/><Area type="monotone" dataKey="spend" stroke="var(--cyan)" strokeWidth={2} fill="url(#spend)"/></AreaChart></ResponsiveContainer></div></Panel>
      <Panel className="xl:col-span-6"><SectionTitle eyebrow="Allocation" title="Service distribution"/><div className="flex h-[210px] items-center"><ResponsiveContainer width="55%" height="100%"><PieChart><Pie data={pie} dataKey="value" innerRadius={55} outerRadius={75} paddingAngle={4}>{pie.map((entry) => <Cell key={entry.name} fill={entry.color}/>)}</Pie></PieChart></ResponsiveContainer><div className="space-y-3">{pie.map((p) => <div key={p.name} className="flex items-center gap-2 text-xs"><span className="size-2 rounded-full" style={{ background: p.color }}/><span className="text-muted-foreground">{p.name}</span><strong className="ml-auto font-mono">{p.value} USDC</strong></div>)}</div></div></Panel>
      <Panel className="xl:col-span-6"><SectionTitle eyebrow="Outcome" title="Settlement ratio"/><div className="grid h-[180px] grid-cols-3 items-end gap-5 px-4"><div className="ratio-column h-full"><span className="ratio-bar bg-cyan" style={{height:"86%"}}/><strong>86%</strong><small>Success</small></div><div className="ratio-column h-full"><span className="ratio-bar bg-destructive" style={{height:"10%"}}/><strong>10%</strong><small>Blocked</small></div><div className="ratio-column h-full"><span className="ratio-bar bg-warning" style={{height:"4%"}}/><strong>4%</strong><small>Failed</small></div></div></Panel>
    </div><PaymentDetail payment={selected} onOpenChange={(open) => !open && setSelected(null)}/></AppShell>;
}