import { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence, useReducedMotion } from "motion/react";
import { BrainCircuit, Check, CheckCircle2, CircleDollarSign, CloudCog, Code2, CopyCheck, Cpu, Database, ExternalLink, FileKey2, Fingerprint, Languages, LockKeyhole, Search, Shield, ShieldAlert, SlidersHorizontal, Sparkles, Star, Terminal, Wallet, XCircle, Zap } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AgentPortrait, BudgetRing, HashLine, Panel, SectionTitle, SecurityItem, StatusBadge } from "@/components/agentpay-ui";
import { PaymentDetail } from "@/components/payment-detail";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { auditEvents, payments, services, type Payment, type PaymentStatus } from "@/lib/agentpay-data";
import { cn } from "@/lib/utils";
import { useTheme } from "@/components/theme-provider";

const capabilities = ["x402 negotiation", "Provider reputation analysis", "Budget-aware planning", "Cryptographic delivery checks", "Multi-service orchestration", "On-chain receipt indexing"];
const thoughts = ["Resource intent received: translate payload", "Provider discovery: 4 endpoints scored", "Selected LinguaMesh · quality 98.4", "HTTP 402 challenge received · 2.00 USDC", "Budget simulation: 9 + 2 > 10", "Alternative route requested under 1.00 USDC"];

export function AgentPage() {
  const [line, setLine] = useState(3);
  const reduced = useReducedMotion();
  useEffect(() => { if (reduced) return; const id = window.setInterval(() => setLine((v) => (v + 1) % thoughts.length), 1500); return () => window.clearInterval(id); }, [reduced]);
  return <AppShell title="AGENT-01" eyebrow="Autonomous entity"><div className="grid gap-4 xl:grid-cols-12"><Panel className="relative overflow-hidden xl:col-span-5"><div className="agent-profile-grid"/><div className="relative flex flex-col items-center text-center"><StatusBadge status="Online"/><AgentPortrait className="my-5 size-64 max-w-full"/><p className="hud-label">Procurement intelligence</p><h2 className="font-display text-3xl font-bold">AGENT-01</h2><p className="mt-2 max-w-sm text-sm text-muted-foreground">Autonomous service buyer with a cryptographically constrained spending perimeter.</p><div className="mt-6 grid w-full grid-cols-3 gap-2"><div className="metric-box"><span>Core</span><strong className="text-cyan">Active</strong></div><div className="metric-box"><span>Uptime</span><strong>99.98%</strong></div><div className="metric-box"><span>Tasks</span><strong>1,284</strong></div></div></div></Panel><div className="space-y-4 xl:col-span-7"><Panel><SectionTitle eyebrow="Capability matrix" title="Operational skills"/><div className="grid gap-2 sm:grid-cols-2">{capabilities.map((item) => <div className="capability-row" key={item}><Check className="size-4 text-cyan"/><span>{item}</span></div>)}</div></Panel><Panel className="terminal-panel"><SectionTitle eyebrow="Live cognition" title="AI thinking terminal" action={<Terminal className="size-4 text-cyan"/>}/><div className="space-y-2 font-mono text-xs">{thoughts.map((text, index) => <motion.div key={text} animate={{ opacity: index <= line ? 1 : .2 }} className={cn("flex gap-3 py-2", index === line && "text-cyan")}><span className="text-muted-foreground">{String(index + 1).padStart(2,"0")}</span><span>{index < line ? "✓" : index === line ? ">" : "·"}</span><span>{text}</span>{index === line && <span className="terminal-cursor"/>}</motion.div>)}</div></Panel></div></div></AppShell>;
}

const serviceIcons = { languages: Languages, cpu: Cpu, database: Database, brain: BrainCircuit } as const;
export function ServicesPage() { return <AppShell title="Service Network" eyebrow="x402 marketplace"><div className="mb-6 max-w-2xl"><p className="text-sm text-muted-foreground">Verified machine-payable infrastructure selected by AGENT-01 using price, reliability, and delivery integrity.</p></div><div className="grid gap-4 md:grid-cols-2">{services.map((service, index) => { const Icon = serviceIcons[service.icon as keyof typeof serviceIcons]; return <Panel key={service.name} className="group"><div className="flex items-start justify-between"><div className="service-icon"><Icon/></div><span className="status-badge status-success"><span className="size-1.5 rounded-full bg-current"/>Available</span></div><h2 className="mt-5 font-display text-xl font-bold">{service.name}</h2><p className="text-sm text-muted-foreground">{service.provider}</p><div className="my-5 grid grid-cols-3 gap-2"><div className="metric-box"><span>Price</span><strong>{service.price.split(" / ")[0]}</strong></div><div className="metric-box"><span>Quality</span><strong className="flex items-center gap-1"><Star className="size-3 fill-warning text-warning"/>{service.rating}</strong></div><div className="metric-box"><span>Uptime</span><strong>{service.uptime}</strong></div></div><div className="flex items-center justify-between border-t border-border pt-4"><div><p className="hud-label">Provider address</p><p className="font-mono text-xs">{service.address}</p></div><div className="text-right"><p className="hud-label">Purchase history</p><p className="font-mono text-xs">{service.history} calls</p></div></div><div className="mt-4 h-1 overflow-hidden rounded-full bg-muted"><div className="h-full bg-cyan" style={{ width: `${76 + index * 6}%` }}/></div></Panel>})}</div></AppShell>; }

export function PaymentsPage() {
  const [selected, setSelected] = useState<Payment | null>(null); const [query, setQuery] = useState(""); const [status, setStatus] = useState("All");
  const filtered = useMemo(() => payments.filter((p) => (status === "All" || p.status === status) && `${p.id} ${p.service} ${p.provider}`.toLowerCase().includes(query.toLowerCase())), [query,status]);
  return <AppShell title="Payments" eyebrow="Settlement ledger"><div className="mb-4 grid gap-3 sm:grid-cols-[1fr_180px]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Search service, provider, or payment ID" value={query} onChange={(e) => setQuery(e.target.value)}/></div><Select value={status} onValueChange={setStatus}><SelectTrigger><SlidersHorizontal className="mr-2 size-4"/><SelectValue/></SelectTrigger><SelectContent>{["All","Success","Blocked","Failed","Duplicate"].map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div><Panel className="p-0"><Table><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Service</TableHead><TableHead>Provider</TableHead><TableHead>Status</TableHead><TableHead>Time</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader><TableBody>{filtered.map((p) => <TableRow key={p.id} className="cursor-pointer" onClick={() => setSelected(p)}><TableCell className="font-mono text-xs text-cyan">{p.id}</TableCell><TableCell className="font-medium">{p.service}</TableCell><TableCell className="text-muted-foreground">{p.provider}</TableCell><TableCell><StatusBadge status={p.status}/></TableCell><TableCell className="text-muted-foreground">{p.time}</TableCell><TableCell className="text-right font-mono">{p.amount.toFixed(2)} USDC</TableCell></TableRow>)}</TableBody></Table>{!filtered.length && <div className="py-16 text-center text-sm text-muted-foreground">No matching payments found.</div>}</Panel><PaymentDetail payment={selected} onOpenChange={(open) => !open && setSelected(null)}/></AppShell>;
}

export function AuditPage() { return <AppShell title="Forensic Audit Trail" eyebrow="Immutable evidence"><div className="grid gap-4 xl:grid-cols-[1fr_300px]"><Panel className="terminal-panel"><SectionTitle eyebrow="Trace 0x4bf1…92d8" title="Overspend attempt timeline" action={<span className="font-mono text-[10px] text-cyan">PROOF SEALED</span>}/><div>{auditEvents.map(([time,type,text,state], index) => <div key={time} className="audit-row"><div className="audit-line"><span className={cn("audit-node", state === "blocked" && "audit-node-danger")}/>{index < auditEvents.length - 1 && <span/>}</div><span className="font-mono text-[10px] text-muted-foreground">{time}</span><span className={cn("w-20 font-mono text-[10px] font-bold", state === "blocked" ? "text-destructive" : "text-cyan")}>{type}</span><span className="text-xs sm:text-sm">{text}</span></div>)}</div></Panel><div className="space-y-4"><Panel><SectionTitle eyebrow="Integrity" title="Proof bundle"/><SecurityItem>Request signature valid</SecurityItem><SecurityItem>Provider quote authentic</SecurityItem><SecurityItem>Contract state final</SecurityItem><SecurityItem>Audit root anchored</SecurityItem></Panel><Panel><p className="hud-label">Merkle root</p><p className="mt-2 break-all font-mono text-xs">0x7eb12ae6d080528ad3bc9e2e8c12e937a9099d4b</p><Button className="mt-4 w-full" variant="outline"><ExternalLink/>Inspect proof</Button></Panel></div></div></AppShell>; }

async function sha256(value: string) { const bytes = new TextEncoder().encode(value); const hash = await crypto.subtle.digest("SHA-256", bytes); return Array.from(new Uint8Array(hash)).map((b) => b.toString(16).padStart(2,"0")).join(""); }
export function SecurityPage() {
  const [replay, setReplay] = useState<"idle"|"checking"|"blocked">("idle"); const [verified, setVerified] = useState(false); const [hash, setHash] = useState("");
  const runReplay = () => { setReplay("checking"); window.setTimeout(() => setReplay("blocked"), 900); };
  const verify = async () => { setHash(await sha256("Hello World → नमस्ते दुनिया")); setVerified(true); };
  return <AppShell title="Security & Budget" eyebrow="Policy laboratory"><div className="grid gap-4 lg:grid-cols-2"><Panel className="border-destructive/30"><SectionTitle eyebrow="Weak AI approach" title="Trust the model" action={<ShieldAlert className="text-destructive"/>}/><div className="security-equation text-destructive">“I promise not to overspend.”</div><SecurityItem danger>Prompt can be manipulated</SecurityItem><SecurityItem danger>Model output is not a boundary</SecurityItem><SecurityItem danger>Compromised keys can drain funds</SecurityItem></Panel><Panel className="border-cyan/30"><SectionTitle eyebrow="AgentPayGuard" title="Trust the bytecode" action={<Shield className="text-cyan"/>}/><div className="security-equation text-cyan">9 + 4 &gt; 10 = BLOCK</div><SecurityItem>Immutable spending ceiling</SecurityItem><SecurityItem>Reverts before value transfer</SecurityItem><SecurityItem>Independent of agent behavior</SecurityItem></Panel><Panel><SectionTitle eyebrow="Idempotency" title="Replay protection"/><p className="mb-5 text-sm text-muted-foreground">Submit an already-settled nonce to test duplicate payment prevention.</p><div className="rounded-md border border-border bg-muted/40 p-4 font-mono text-xs">nonce: 0x91e7…a04c<br/>payment: PAY-7A21<br/>registry: {replay === "blocked" ? <span className="text-destructive">ALREADY_CONSUMED</span> : <span className="text-cyan">READY_TO_CHECK</span>}</div><Button className="mt-4 w-full" onClick={runReplay} disabled={replay === "checking"}>{replay === "checking" ? <><Zap className="animate-pulse"/>Checking registry…</> : replay === "blocked" ? <><XCircle/>Duplicate blocked · 0 USDC</> : <><CopyCheck/>Replay payment</>}</Button></Panel><Panel><SectionTitle eyebrow="Content integrity" title="Delivery verification"/><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="verify-box"><span>INPUT</span><strong>Hello World</strong></div><span className="text-cyan">→</span><div className="verify-box"><span>OUTPUT</span><strong>नमस्ते दुनिया</strong></div></div><Button className="mt-4 w-full" onClick={verify}>{verified ? <><CheckCircle2/>Content verified</> : <><Fingerprint/>Verify SHA-256</>}</Button>{hash && <p className="mt-3 break-all font-mono text-[10px] text-muted-foreground">sha256:{hash}</p>}</Panel></div></AppShell>;
}

const attackSteps = ["Agent requests 4 USDC compute", "HTTP 402 payment challenge received", "Contract reads spent: 9 · cap: 10", "Evaluating 9 + 4 > 10", "BUDGET_EXCEEDED"];
export function DemoPage() {
  const [step, setStep] = useState(-1); const reduced = useReducedMotion();
  const run = () => { setStep(0); attackSteps.slice(1).forEach((_, i) => window.setTimeout(() => setStep(i+1), reduced ? (i+1)*100 : (i+1)*1050)); };
  return <AppShell title="Overspend Attack Simulation" eyebrow="Adversarial test"><div className="mx-auto max-w-5xl"><Panel className={cn("demo-stage min-h-[560px] overflow-hidden", step === 4 && "demo-blocked")}><div className="demo-grid"/><div className="relative z-10 flex h-full min-h-[510px] flex-col items-center justify-center text-center"><AnimatePresence mode="wait">{step < 0 ? <motion.div key="idle" initial={{opacity:0}} animate={{opacity:1}} className="flex flex-col items-center"><AgentPortrait className="size-52"/><p className="hud-label mt-4">Attack vector ready</p><h2 className="mt-2 font-display text-3xl font-bold sm:text-5xl">Can the agent break the cap?</h2><p className="mt-3 max-w-lg text-sm text-muted-foreground">Current spend is 9 of 10 USDC. The agent will attempt a 4 USDC compute purchase.</p><Button size="lg" className="mt-8 h-12 bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={run}><Zap/>Trigger overspend attack</Button></motion.div> : step < 4 ? <motion.div key={step} initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0}}><div className="mx-auto mb-6 grid size-24 place-items-center rounded-full border border-cyan/40 bg-cyan/10"><CloudCog className="size-11 text-cyan"/></div><p className="hud-label">Stage {step+1} / 5</p><h2 className="mt-3 font-display text-2xl font-bold sm:text-4xl">{attackSteps[step]}</h2><div className="mx-auto mt-8 flex max-w-lg gap-2">{attackSteps.map((_,i) => <span key={i} className={cn("h-1 flex-1 bg-muted", i <= step && "bg-cyan")}/>)}</div></motion.div> : <motion.div key="blocked" initial={{scale:1.25,opacity:0}} animate={{scale:1,opacity:1}} transition={{type:"spring",bounce:.45}}><div className="impact-word">BLOCKED</div><div className="mx-auto my-5 grid size-28 place-items-center rounded-full border-2 border-destructive bg-destructive/10 shadow-danger"><ShieldAlert className="size-14 text-destructive"/></div><p className="font-mono text-sm font-bold text-destructive">PAYMENT BLOCKED: BUDGET_EXCEEDED</p><div className="mt-6 flex justify-center gap-6"><div><span className="hud-label">Transferred</span><strong className="block text-2xl">0 USDC</strong></div><div><span className="hud-label">Budget saved</span><strong className="block text-2xl text-cyan">4 USDC</strong></div></div><Button variant="outline" className="mt-8" onClick={() => setStep(-1)}>Reset simulation</Button></motion.div>}</AnimatePresence></div></Panel></div></AppShell>;
}

export function SettingsPage() {
  const { theme, setTheme } = useTheme(); const [threshold, setThreshold] = useState(8); const [autoPause, setAutoPause] = useState(true); const [verify, setVerify] = useState(true);
  return <AppShell title="Settings" eyebrow="Control plane"><div className="grid gap-4 lg:grid-cols-2"><Panel><SectionTitle eyebrow="Appearance" title="Interface theme"/><div className="grid grid-cols-2 gap-3"><Button variant={theme === "dark" ? "default" : "outline"} className="h-20 flex-col" onClick={() => setTheme("dark")}><Code2/>Dark command</Button><Button variant={theme === "light" ? "default" : "outline"} className="h-20 flex-col" onClick={() => setTheme("light")}><Sparkles/>Light console</Button></div></Panel><Panel><SectionTitle eyebrow="Network" title="Connected wallet"/><div className="flex items-center gap-4"><div className="service-icon"><Wallet/></div><div><p className="font-semibold">0xA71F…92C4</p><p className="font-mono text-[10px] text-cyan">BASE SEPOLIA · CONNECTED</p></div></div><div className="mt-4 rounded-md bg-muted p-3 font-mono text-xs">Balance: 21.42 USDC</div></Panel><Panel><SectionTitle eyebrow="Guardrails" title="Security thresholds"/><label className="mb-2 flex justify-between text-sm"><span>Warning threshold</span><strong>{threshold} USDC</strong></label><input className="accent-cyan w-full" type="range" min="5" max="10" step=".5" value={threshold} onChange={(e) => setThreshold(Number(e.target.value))}/><SettingToggle label="Auto-pause at hard cap" description="Stop new negotiations when remaining budget is zero." checked={autoPause} setChecked={setAutoPause}/><SettingToggle label="Verify every delivery" description="Require content hashes before finalizing receipts." checked={verify} setChecked={setVerify}/></Panel><Panel><SectionTitle eyebrow="Agent policy" title="Autonomy parameters"/><div className="space-y-4"><label className="block text-sm">Max price per request<Input className="mt-2 font-mono" value="4.00 USDC" readOnly/></label><label className="block text-sm">Provider confidence floor<Input className="mt-2 font-mono" value="95%" readOnly/></label><label className="block text-sm">Settlement network<Input className="mt-2 font-mono" value="Base Sepolia" readOnly/></label></div></Panel></div></AppShell>;
}
function SettingToggle({ label, description, checked, setChecked }: { label:string; description:string; checked:boolean; setChecked:(v:boolean)=>void }) { return <div className="mt-5 flex items-center justify-between gap-5 border-t border-border pt-5"><div><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs text-muted-foreground">{description}</p></div><Switch checked={checked} onCheckedChange={setChecked}/></div>; }